[package]
name = "gc_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "gc_rs"
path = "src/lib.rs"

[[bin]]
name = "gc_rs_bin"
path = "src/bin.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
