[package]
name = "gc_rs"
version = "0.1.0"
edition = "2021"
authors = ["Evan Williams <evanawilliams@live.com>"]
repository = "https://github.com/evan-a-w/gc_rs"

[lib]
name = "gc_rs"
path = "src/lib.rs"

[dependencies]
gc_rs_derive = { path = "../gc_rs_derive" }
