[package]
name = "gc_rs_tests"
version = "0.1.0"
edition = "2021"

[lib]
name = "gc_rs_tests"
path = "src/lib.rs"

[[bin]]
name = "leak_check"
path = "src/bin.rs"

[dependencies]
gc_rs = { path = "../gc_rs" }
